import './globals.css'
import { Inter } from 'next/font/google'
 import {Header} from '@/components/header'
 import {Menu} from '@/components/menu'
import {Footer} from '@/components/footer'
import 'bootstrap/dist/css/bootstrap.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='conatainer-fluid'>
          <div className='row'>
            <Header />
          </div>
          <div className='row'>
            <div className='col-4'>
                <Menu />
            </div>
            <div className='col-6'>
              {children}
            </div>
          </div>
          <div className='row'>
            <Footer />
          </div>
        </div>
        
      </body>
    </html>
  )
}
